---
title: "Title"
subtitle: "Subtitle"
author: "Author Name"
thanks: "Acknowledgements"
# abstract: "Here is an abstract."
date: last-modified
date-format: iso
format:
  pdf:
    toc: true
    toc-depth: 3
    toc-title: "Contents"
    # lof: true
    # lot: true
    number-sections: true
    colorlinks: true
    documentclass: scrartcl
    papersize: letter
    highlight-style: github
df-print: kable # show data frames as kabales
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(collapse = TRUE, # the code and its output are shown together
                      warning = FALSE, # suppresses warning messages
                      error = FALSE, # suppresses error messages
                      message = FALSE # suppresses messages generated by the code
                      )
# install "pacman" package if not already installed
if (!require("pacman")) install.packages("pacman")
# using "p_load ()" to load packages
pacman::p_load(tidyverse, rio, here)
```

# Background

Background information.

# Questions

## Title of Question 1.

::: {.callout-note appearance="simple" icon="false"}
Additional information for question 1.
:::

**Solution:**

```{r}
data("mtcars")
head(mtcars)
```


\<Text solutions for question 1\>.

\newpage

## Title of Question 2.

::: {.callout-note appearance="simple" icon="false"}
Additional information for question 2.
:::

**Solution:**

\<Text solutions for question 2\>.
