---
title: "Homework 1"
author: "Celline Wijaya"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, # the code and its output are shown together
                        warning = FALSE, # suppresses warning messages
                        error = FALSE, # suppresses error messages
                        message = FALSE # suppresses messages generated by the code
                        )
  pacman::p_load(tidyverse, rio, here)
```

## R Markdown

```{r data input}
data <- tibble(
  q = 1:5,
  n = rep(1000000, each = 5),
  prevalence = c(7,9,11,16,18)/100,
  seek_care = c(29,28,32,35,40)/100,
  public = c(95,90,83,71,58)/100,
  insurance = c(30,41,54,58,67)/100
) |>
  
mutate(
  prob_death_nocare = 0.031,
  rr_death_public = 0.68,
  rr_death_private = 0.35,
  unit_cost_public = 24,
  unit_cost_private = 63,
  reimburse = 70/100
)
```

## 1. Flow chart of patients

Flow chart

```{r flow chart}
# Install and load the DiagrammeR package
install.packages("DiagrammeR")
library(DiagrammeR)

# Create the flowchart
grViz("
digraph flowchart {
    graph [layout = dot,
           rankdir = LR,
           overlap = false,
           fontname = 'Helvetica',
           fontsize = 1];

    node [shape = rectangle,
          fixedsize = false,
          fontname = 'Helvetica'];

    Diagnosis [label = 'Initial diagnosis'];
    Care [label = 'Seek care'];
    NoCare [label = 'Do not seek care'];
    Public [label = 'Treatment in public facility'];
    Private [label = 'Treatment in private facility'];
    Recovery [label = 'Recovery'];
    Death [label = 'Death'];

    Diagnosis -> {Care NoCare};
    Care -> {Public Private};
    NoCare -> {Recovery Death};
    {Public Private} -> {Recovery Death};
}
")

```

## 2. Calculate the number of patients, number of care seekers, number of patients attending public facility, and number of patients attending public facility with insurance.



